### ISSUE TITLE
Delete nodes chokes when multiple ENTERED_BY

### ISSUE THREAD

**Issue by NoisyFlowers** [paleobot/pbot-api#2]
Delete only works if there is one ENTERED_BY relationship. It's weird. Here's the current cypher used to delete a Description node by the graphql mutation:
```
                MATCH 
                    (description:Description {pbotID: $data.pbotID})-[enteredBy:ENTERED_BY]->(person:Person {pbotID:$data.enteredByPersonID})
                OPTIONAL MATCH
                    (description)-[applicationOf:APPLICATION_OF]->(:Schema)
                OPTIONAL MATCH
                    (description)-[definedBy:DEFINED_BY]->(:CharacterInstance)
                OPTIONAL MATCH
                    (description)<-[describedBy:DESCRIBED_BY]-(:Specimen)
                WITH definedBy, enteredBy, applicationOf, describedBy, description
                CALL apoc.do.when(
                    definedBy is not null, 
                    'RETURN "Cannot delete node " + description.pbotID + " because it has CharacterInstances" AS result', 
                    'UNWIND enteredBy AS eb DELETE eb WITH collect(eb) AS dummy, applicationOf, describedBy, description DELETE applicationOf, describedBy WITH description, description.pbotID AS dID DELETE description RETURN dID + " deleted" AS result',
                    {definedBy: definedBy, enteredBy:enteredBy, applicationOf: applicationOf, describedBy: describedBy,  description: description}
                ) YIELD value
				WITH {
					pbotID: value.result
				} AS result
                RETURN result                
```
Executing this manually without the apoc.do.when, it works just fine. But with the apoc call, it chokes with a "node still has relationships" error. I'm guessing that only one ENTERED_BY is passed into the apoc routine at a time. If so, would need to wrap the apoc call in an UNWIND. Not quite sure how to do that.

**Comment by NoisyFlowers** [comment]
The call to apoc.do.when is an attempt to return a meaningful message if there are CharacterInstances still hanging off the Description. The idea is to check for DEFINED_BY relationships first and, if there are any, return a message to that effect, if there are not, delete everything else. That last part doesn't work from inside the apoc call. 

I don't see a good way to do this, so, for now, I'm going to just strip the apoc call out, not worry about checking for DEFINED_BY relationships, and let the api return whatever the cypher generates. 
```
                MATCH 
                    (description:Description {pbotID: $data.pbotID})-[enteredBy:ENTERED_BY]->(person:Person {pbotID:$data.enteredByPersonID})
                OPTIONAL MATCH
                    (description)-[applicationOf:APPLICATION_OF]->(:Schema)
                OPTIONAL MATCH
                    (description)<-[describedBy:DESCRIBED_BY]-(:Specimen)
                WITH enteredBy, applicationOf, describedBy, description
                UNWIND enteredBy AS eb 
                    DELETE eb
                WITH collect(eb) AS dummy, applicationOf, describedBy, description 
                    DELETE applicationOf, describedBy 
                WITH description, description.pbotID AS dID
                    DELETE description
                WITH {
                    pbotID: dID + " deleted"
                } AS result
                RETURN result
```
This allows the delete to work properly unless there are DEFINED_BY relationships, in which case the cypher rollback leaves things as they were before the call and the api sends this to the client:
```
Error: Cannot delete node<392>, because it still has relationships. To delete this node, you must first delete its relationships.
```
It's a bit cryptic, with the reference to the internal Neo4J id and all, but, in the interest of moving things along, I'm ok with it for now.

**Comment by NoisyFlowers** [comment]
I'll add that there is an argument to be made that we should allow the delete of a Description node to take all its CharacterInstance nodes with it. In this case, we'd MATCH them, UNWIND them to delete them first, then delete the Description node.

**Comment by aazaff** [comment]
Okay this is complex. My first reaction is, absolutely, we should allow the delete of a description node to take all its children.

However, here is what I'm thinking.

I think we need to approach this similar to how we did it in AZLIB where there are a few different types of edit/deletes. Here is my first pass list, but I don't know if all are really needed. We'll need to discuss.

1. A delete that truly removes a node and any of its children. (The I fucked up and didn't mean to enter this delete)
2. A delete that keeps the node and its children in the system, but flags it or otherwise deactivates/hides it somehow. (The, I don't want this to show up anymore but for some record keeping reason (its connected to other valid nodes?) we want it to stay in the data base delete).
3. An edit that is just an edit and doesn't trigger any special effects. (The I just want to fix a typo and not make a big fuss edit).
4. An edit that is a big deal and might end up directly or indirectly affecting linked nodes, possibly meaning that an entirely new fork or version needs of the original needs to be entered into the database and some sort of SUPERSEDES relationship entered (this is the most complex).

**Comment by aazaff** [comment]
Just as a refresher on how we did this in AZLIB (from the REST perspective)

PATCH - Just edit it and do nothing with versioning
PUT - fork an existing entity and create a "superseded/preceeds" relationship
POST - new entity
DELETE - delete an entity, does NOT allow a preceeding entity to be deleted if it has a supersedeing entity.

I think this is a good framework.
